### Add Delivery Address
POST {{host}}/api/user/delivery-addresses
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Home",
  "fullName": "John Doe",
  "street": "123 Main St",
  "city": "New York",
  "postalCode": "10001",
  "country": "US",
  "phoneNumber": "+1234567890",
  "isDefault": true
}

### Get Delivery Addresses
GET {{host}}/api/user/delivery-addresses/
Authorization: Bearer {{auth_token}}

### Get User Preferences
GET {{host}}/api/user/preferences
Authorization: Bearer {{auth_token}}
Accept-Language: pl-PL

### Update User Preferences
PUT {{host}}/api/user/preferences
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "language": "pl-PL",
  "preferredCurrency": "PLN"
}
