flyway.driver=com.dbschema.MongoJdbcDriver
flyway.locations=filesystem:src/main/resources/gimlee-ratings/db/migration/mongo
flyway.table=gimlee_ratings_flyway_schema_history
flyway.sqlMigrationSuffixes=.js
