### Fetch Ads - Basic
# Fetches ads with default pagination (page 0) and default sorting (created date descending).
# Includes price in preferred currency (determined by Accept-Language or user preferences).
# @name GetAdsBasic
GET {{host}}/api/ads/
Accept-Language: pl-PL

### Expected Response (Success - 200 OK):
# Content-Type: application/json
#
# {
#   "content": [
#     {
#       "id": "60f8f9b3a9d9e8f8a8b8c8d8",
#       "title": "Ad Title",
#       "price": { "amount": 100, "currency": "ARRR" },
#       "preferredPrice": { "amount": 50.00, "currency": "PLN" },
#       ...
#     }
#   ],
#   ...
# }


### Fetch Ads - With Text Search and Page
# t: text search query
# p: page number (0-indexed)
# @name GetAdsTextSearch
GET {{host}}/api/ads/?t=Searched%20Keyword&p=1

### Expected Response (Success - 200 OK):
# Content-Type: application/json
# (Paged response containing ads matching the keyword)


### Fetch Ads - With City, Price Range, and Sorting
# cty: city ID
# minp: minimum price
# maxp: maximum price
# by: sort by field (e.g., CREATED_DATE, PRICE)
# dir: sort direction (ASC, DESC)
# @name GetAdsFilteredAndSorted
GET {{host}}/api/ads/?cty=city-id-123&minp=100&maxp=500&by=CREATED_DATE&dir=ASC

### Expected Response (Success - 200 OK):
# Content-Type: application/json
# (Paged response containing ads within the price range in the specified city)


### Fetch Ads - With Category Filter
# cat: category ID
# @name GetAdsCategoryFilter
GET {{host}}/api/ads/?cat=60f8f9b3a9d9e8f8a8b8c8d8

### Expected Response (Success - 200 OK):
# Content-Type: application/json
# (Paged response containing ads in the specified category or its subcategories)


### Fetch Ads - With Geographic Circle Filter
# x: longitude
# y: latitude
# r: radius in kilometers (must be >= 0.5)
# @name GetAdsGeoFilter
GET {{host}}/api/ads/?x=-73.985130&y=40.758896&r=10

### Expected Response (Success - 200 OK):
# Content-Type: application/json
# (Paged response containing ads within 10km of the specified coordinates)


### Fetch Ads - Combined Filters
# Example combining text search, price range, city, category, and specific page, sorted ascending by price.
# @name GetAdsCombinedFilters
GET {{host}}/api/ads/?t=Vintage%20Bike&minp=50&maxp=250&cty=another-city-id&cat=some-category-id&by=PRICE&dir=ASC&p=0

### Expected Response (Success - 200 OK):
# Content-Type: application/json


### Fetch Featured Ads
# Fetches featured ads. Currently, these are the most recently added ads.
# No client-side filtering or pagination parameters.
# @name GetFeaturedAds
GET {{host}}/api/ads/featured/

### Expected Response (Success - 200 OK):
# Content-Type: application/json
# (List of featured ads)




### Fetch Single Ad Details
# Fetches details for a specific ad by its ID.
# Includes price in preferred currency.
# Includes most recent other ads from the same user.
# Replace {adId} with an actual Ad ID.
# @name GetAdById
GET {{host}}/api/ads/some-ad-id-12345
Accept-Language: en-US

### Expected Response (Success - 200 OK):
# Content-Type: application/json
#
# {
#   "id": "some-ad-id-12345",
#   "title": "Ad Title",
#   "availableStock": 10,
#   "price": { "amount": 100, "currency": "ARRR" },
#   "preferredPrice": { "amount": 25.50, "currency": "USD" },
#   "user": {
#     "userId": "60f8f9b3a9d9e8f8a8b8c8d8",
#     "username": "pirate",
#     "avatarUrl": "http://avatar.url",
#     "presence": {
#       "status": "ONLINE",
#       "lastSeenAt": 1627468800000000
#     },
#     "memberSince": 1627468800000000
#   },
#   "otherAds": [
#     {
#       "id": "another-ad-id-67890",
#       "title": "Another Ad Title",
#       "price": { "amount": 200, "currency": "ARRR" },
#       "preferredPrice": { "amount": 51.00, "currency": "USD" },
#       "mainPhotoPath": "path/to/photo.jpg",
#       "categoryId": 123,
#       "categoryPath": [...],
#       "location": {...}
#     }
#   ]
# }


### Fetch Single Ad Details - Non-Existent Ad
# Example for an ad ID that is not expected to exist, to test 404 response.
# Replace {adId} with an ID that is unlikely to exist.
# @name GetAdByIdNotFound
GET {{host}}/api/ads/non-existent-ad-id-999

### Expected Response (Not Found - 404 Not Found):
# HTTP/1.1 404 Not Found