### Register User
# @name /auth/register
# Replace "ema... " with real email
POST http://localhost:12060/api/auth/register
Content-Type: application/json

{
  "username": "test",
  "password": "Password1",
  "email": "ema..."
}

### Login User
# @name /auth/login
POST http://localhost:12060/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Password1"
}

### Verify User
# @name /auth/verifyUser
POST http://localhost:12060/api/auth/verifyUser
Content-Type: application/json

{
  "code": "111378"
}

### Check Username Availability
# @name /auth/register/usernameAvailable
POST http://localhost:12060/api/auth/register/usernameAvailable
Content-Type: application/json

{
  "username": "test"
}

### Check Email Availability
# @name /auth/register/emailAvailable
# Replace "ema... " with real email
POST http://localhost:12060/api/auth/register/emailAvailable
Content-Type: application/json

{
  "email": "ema..."
}

### Upload Media (JPEG Example)
# @name /media/upload [image/jpeg]
# Note: For file uploads, replace "< "<file>"" with the actual path to your file, e.g., "< "path/to/your/image.jpg""
POST http://localhost:12060/api/media/upload
Content-Type: multipart/form-data

type = picture
file = < "<file>"

### Upload Media (PNG Example)
# @name /media/upload [image/png]
# Note: For file uploads, replace "< "<file>"" with the actual path to your file, e.g., "< "path/to/your/image.png""
POST http://localhost:12060/api/media/upload
Content-Type: multipart/form-data

type = picture
file = < "<file>"

### Get media
GET http://localhost:12060/api/media?p=/123.png

