{
 "title": "Local API dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "API Response times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum[1m]) / rate(http_server_requests_seconds_count[1m]) * 1000",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "REST API Heap MB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(jvm_memory_used_bytes) / 1024 / 1024",
     "legendFormat": "{{area}} - {{id}}"
    }
   ]
  },
  {
   "title": "API Requests per 1 minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[1m]) * 60",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}