### Get Q&A Stats for an Ad (Public)
# Returns the total number of answered and unanswered questions for an ad.
# Useful for displaying a Q&A count on ad cards.
#
# @name getQaStats
GET {{host}}/api/qa/ads/{{adId}}/questions/stats
