### Upload Media (JPEG Example)
# @name /media/upload [image/jpeg]
POST http://localhost:12060/api/media/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="files[]"; filename="image.jpg"

# Replace "< /path/to/your/image.jpg" with the actual path to your file
< /path/to/your/image.jpg
--boundary--

### Upload Media (PNG Example)
# @name /media/upload [image/png]
POST http://localhost:12060/api/media/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="files[]"; filename="photo2pixel_download.png"

# Replace "< /path/to/your/image.png" with the actual path to your file
< /path/to/your/image.png
--boundary--

### Get media
GET http://localhost:12060/api/media?p=/123.png