### Register User
# @name /auth/register
# Replace "ema... " with real email
POST {{host}}/api/auth/register
Content-Type: application/json

{
  "username": "test",
  "password": "Password1",
  "email": "ema..."
}

### Login User
# @name /auth/login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Password1"
}

### Verify User
# @name /auth/verifyUser
POST {{host}}/api/auth/verifyUser
Content-Type: application/json

{
  "code": "111378"
}

### Check Username Availability
# @name /auth/register/usernameAvailable
POST {{host}}/api/auth/register/usernameAvailable
Content-Type: application/json

{
  "username": "test"
}

### Check Email Availability
# @name /auth/register/emailAvailable
# Replace "ema... " with real email
POST {{host}}/api/auth/register/emailAvailable
Content-Type: application/json

{
  "email": "ema..."
}
